default:
  SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://root:password@192.168.0.136/project'
  SQLALCHEMY_TRACK_MODIFICATIONS: False
  SECRET_KEY: 'this is secret key !!!'
  DEBUG: True
development:  
production:
  