"""empty message

Revision ID: 0409df2be76d
Revises: 0aa98504ddc1
Create Date: 2021-05-13 23:16:11.909339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0409df2be76d'
down_revision = '0aa98504ddc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('sensor_free_id', sa.Integer(), nullable=True))
    op.add_column('room', sa.Column('sensor_one_id', sa.Integer(), nullable=True))
    op.add_column('room', sa.Column('sensor_two_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'room', 'sensor', ['sensor_free_id'], ['id'])
    op.create_foreign_key(None, 'room', 'sensor', ['sensor_one_id'], ['id'])
    op.create_foreign_key(None, 'room', 'sensor', ['sensor_two_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'room', type_='foreignkey')
    op.drop_constraint(None, 'room', type_='foreignkey')
    op.drop_constraint(None, 'room', type_='foreignkey')
    op.drop_column('room', 'sensor_two_id')
    op.drop_column('room', 'sensor_one_id')
    op.drop_column('room', 'sensor_free_id')
    # ### end Alembic commands ###
