"""empty message

Revision ID: 0aa98504ddc1
Revises: 67775b3df73e
Create Date: 2021-04-24 00:39:44.500618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa98504ddc1'
down_revision = '67775b3df73e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor', sa.Column('on_home', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor', 'on_home')
    # ### end Alembic commands ###
