"""empty message

Revision ID: 58f9f98d0673
Revises: d3eedb26da2c
Create Date: 2021-09-05 17:07:59.046198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58f9f98d0673'
down_revision = 'd3eedb26da2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('surname', sa.String(length=256), nullable=True))
    op.create_unique_constraint(None, 'user', ['login'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'surname')
    # ### end Alembic commands ###
