"""empty message

Revision ID: d3eedb26da2c
Revises: a6310573ab44
Create Date: 2021-09-04 18:14:40.299744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3eedb26da2c'
down_revision = 'a6310573ab44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('group_id', sa.Integer(), server_default='3', nullable=False))
    op.create_foreign_key(None, 'user', 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'group_id')
    # ### end Alembic commands ###
