"""empty message

Revision ID: fff310852561
Revises: 0674b3c9f3c2
Create Date: 2021-06-20 17:31:31.764345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fff310852561'
down_revision = '0674b3c9f3c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controller', sa.Column('baudrate', sa.Integer(), nullable=True))
    op.add_column('device_func', sa.Column('cur_val', sa.Float(), nullable=True))
    op.add_column('device_func', sa.Column('multiply', sa.Float(), nullable=True))
    op.add_column('device_func', sa.Column('write_enable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_func', 'write_enable')
    op.drop_column('device_func', 'multiply')
    op.drop_column('device_func', 'cur_val')
    op.drop_column('controller', 'baudrate')
    # ### end Alembic commands ###
